name: android
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: "#️⃣ Generate Build Number"
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.github_token }}
    - run: make init
    - run: make out
    - run: make build
